class NoteFileNotSaved(Exception):
    ...

class ExecutableDoesNotExist(Exception):
    ...

class NoNotesInDatabase(Exception):
    ...

class ConfigFileDoesNotExist(Exception):
    ...

class TrashIsAlreadyEmpty(Exception):
    ...
